package de.jo.aurora.parser.nodes;

/**
 * @author Johannes Hans 19.05.2023
 * @Project AuroraScript
 */
public enum NodeType {

    PROGRAM,

    //EXPRESSION
    IDENTIFIER, NUMERIC_LITERAL, BOOLEAN_LITERAL, STRING_LITERAL, CHAR_LITERAL, NULL_LITERAL,

    TERNARY_EXPRESSION, BINARY_EXPRESSION, UNARY_EXPRESSION,
    BINARY_COMPARISON,

    FUNCTION_CALL, VARIABLE_ASSIGNMENT,

    //STATEMENT
    VARIABLE_DECLARATION, FUNCTION_DECLARATION, RETURN,

    LOGIC, IF, ELSE, ELSE_IF, FOR, WHILE

}
